# 100 numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr = np.zeros((10,10))
print("%d bytes" % (arr.size * arr.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
y = np.zeros(10)
y[4]= 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vec = vec[::-1]
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
x = [1,2,0,0,4,0]
index = np.nonzero(x)
print(index)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
arr = np.random.random((3,3,3))
print(arr)

[[[1.10369767e-01 3.63983491e-01 5.52464694e-01]
  [4.40458538e-01 3.50027279e-01 3.84785558e-01]
  [4.47178940e-01 3.37661706e-01 1.99950281e-01]]

 [[6.47975798e-01 8.63020893e-01 7.85691007e-01]
  [7.84067429e-02 3.46374859e-01 3.60338928e-01]
  [8.38671333e-04 9.90187502e-01 7.60149912e-01]]

 [[3.77579141e-01 6.76642891e-01 6.48167512e-01]
  [7.72779192e-01 8.72865709e-01 6.13057178e-01]
  [4.08116433e-01 7.80029685e-01 3.15609176e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
arr = np.random.random((10,10))
print(arr)
min_arr = arr.min()
max_arr = arr.max()
print("\n")
print("Minimum value :",min_arr)
print("Maximum value :",max_arr)

[[0.725321   0.20497594 0.62382928 0.45026656 0.58507813 0.97194689
  0.7506107  0.95733557 0.30950132 0.20282694]
 [0.58784303 0.90331605 0.55750069 0.96646281 0.85537417 0.23253126
  0.8834615  0.21816569 0.12246901 0.74365809]
 [0.19551201 0.55188721 0.45091318 0.6226354  0.61053557 0.22470632
  0.27252576 0.29817063 0.24096439 0.20620024]
 [0.83901273 0.19269519 0.48026918 0.87198585 0.68161226 0.45904414
  0.01991375 0.78427442 0.20047319 0.88436086]
 [0.18010382 0.75597375 0.12473007 0.71689143 0.02656207 0.16137555
  0.16711947 0.59804528 0.67957537 0.83718226]
 [0.6680939  0.06091679 0.95608889 0.04618764 0.81350079 0.69163156
  0.00388651 0.00226376 0.67888695 0.04496727]
 [0.64042269 0.4960267  0.05900176 0.59159159 0.82340812 0.98286317
  0.27177925 0.0232605  0.83432775 0.67773112]
 [0.60478614 0.59371883 0.66750519 0.07877747 0.96255055 0.01295363
  0.47307415 0.78067421 0.69943964 0.83630839]
 [0.53750152 0.1859664  0.71298282 0.43158303 0.80745794 0.50056713
  0.09982122

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
myvec = np.random.random(30)
print(myvec)
m = myvec.mean()
 
print("\n")
print("Mean :",m)

[0.04591007 0.33310696 0.37329059 0.10772756 0.64664887 0.33770966
 0.96557102 0.29397255 0.2535843  0.2013599  0.36217226 0.41410851
 0.40212458 0.5017968  0.10844857 0.03489185 0.0482506  0.70854205
 0.25563611 0.61229099 0.18010347 0.86329203 0.61164858 0.95899504
 0.01937094 0.00441999 0.70570601 0.02122487 0.01345414 0.88756976]


Mean : 0.3757642874155199


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
mat = np.diag(1+np.arange(4), k = -1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
mat = np.zeros((8,8),dtype=int)
mat[1::2,::2] = 1
mat[::2,1::2] = 1
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
c = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
mymat = np.random.random((5,5))
m_max, m_min = mymat.max(), mymat.min()
mymat = (mymat - m_min)/(m_max - m_min)
print(mymat)

[[1.         0.77326827 0.         0.42789548 0.86619052]
 [0.16817252 0.23530406 0.17076365 0.49913782 0.97740587]
 [0.64291455 0.8180773  0.99060857 0.68385271 0.97739843]
 [0.79218605 0.53914182 0.98153364 0.68494505 0.22814183]
 [0.54809659 0.47609646 0.11773384 0.04986541 0.30027466]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-23-fb55b93b5031>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
mymat = np.dot(np.ones((5,3)), np.ones((3,2)))
print(mymat)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
y = np.arange(10)
y[(3 < y) & (y < 8)] *= -1
print(y)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z is valid only for positive vector
Z <- Z is valid
1j*Z is valid
Z/1/1 is valid

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
[-2.14748365e+09]

#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
arr = [1,4,6,7,2,3,-9,-4,-3]
print (np.copysign(np.ceil(np.abs(arr)), arr))

[ 1.  4.  6.  7.  2.  3. -9. -4. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
a = [1,8,4,5,3,2]
b = [6,8,9,1,0,4]
print(np.intersect1d(a,b))

[1 4 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
np.seterr(all = "ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
No,it is false [invalid value in entered in sqrt(),only positive values are allowed.]

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yesterday :",yesterday)
print("Today :",today)
print("Tomorrow :",tomorrow)

Yesterday : 2021-07-13
Today : 2021-07-14
Tomorrow : 2021-07-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [32]:
date = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(date)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [33]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [34]:
arr = np.random.uniform(0,10,10)

print (arr - arr%1)     #Method 1 :using modulus function to remove decimal part
print (np.floor(arr))   #Method 2 :using floor()
print (np.ceil(arr)-1)  #Method 3 :using ceil()
print (arr.astype(int)) #Method 4 :using astype(int) to extract only integer part

[5. 2. 1. 2. 8. 9. 8. 2. 0. 4.]
[5. 2. 1. 2. 8. 9. 8. 2. 0. 4.]
[5. 2. 1. 2. 8. 9. 8. 2. 0. 4.]
[5 2 1 2 8 9 8 2 0 4]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:
mat = np.zeros((5,5))
mat += np.arange(5)
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [36]:
def generater():
    for i in range(10):
        yield i

mat = np.fromiter(generater(),dtype = float,count = -1)
print(mat)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [37]:
myvec = np.linspace(0,1,11,endpoint = False)[1:]
print(myvec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [38]:
vec = np.random.random(10)
vec.sort()
print(vec)

[0.0176428  0.10709758 0.16312553 0.17384534 0.25212464 0.39960703
 0.40366425 0.49524998 0.66023347 0.94811893]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [39]:
a2 = np.random.random(10)
np.add.reduce(a2)

4.963667821135175

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [40]:
A = np.random.randint(0,3,12)
B = np.random.randint(0,3,12)

equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [41]:
x = np.zeros(5)
x.flags.writeable = False   #array is set to read only mode
print(x)

[0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [42]:
c = np.random.random((10,2))
x,y = c[:,0], c[:,1]
p1 = np.sqrt(x**2 + y**2)
p2 = np.arctan2(y,x)
print(p1)
print(p2)

[0.78114186 0.5637399  0.96955193 0.78521469 1.05689352 0.5894538
 0.74203786 0.73799339 1.04583001 0.87746808]
[1.55743168 1.34154804 0.43488533 1.22592264 1.21942216 0.21810838
 0.60527657 0.37538286 0.36783845 0.0840508 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [43]:
myvec = np.random.random(10)
print("Original Vector :",myvec)
print("\n")
myvec[myvec.argmax()] = 0
print("Vector after replacing the largest no with 0 :",myvec)

Original Vector : [0.33447707 0.45079692 0.53077032 0.88518676 0.88118199 0.0077736
 0.648877   0.92944848 0.41725932 0.52262245]


Vector after replacing the largest no with 0 : [0.33447707 0.45079692 0.53077032 0.88518676 0.88118199 0.0077736
 0.648877   0.         0.41725932 0.52262245]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [44]:
c1 = np.zeros((5,5), [('x',float),('y',float)])
c1['x'], c1['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))

print(c1)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [45]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(round(np.linalg.det(c),3))

3638.164


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [46]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [47]:
import sys
np.set_printoptions(threshold = sys.maxsize)
arr = np.zeros((30,30))
print(arr) 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [48]:
x = np.arange(100)
print(x)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
56


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [49]:
arr = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-49-dbd3bc4c1ef6>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [50]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.50996235 0.53023052 0.64788724 0.56387213 0.66546838
  0.72954411 0.76359346 0.57393374 0.16188341]
 [0.50996235 0.         0.63841779 0.70620572 0.84726814 0.22418954
  0.85981685 0.94040637 0.10330456 0.37009632]
 [0.53023052 0.63841779 0.         0.11878934 0.27017851 0.60711009
  0.22803883 0.30209362 0.6112835  0.44492245]
 [0.64788724 0.70620572 0.11878934 0.         0.32375281 0.63851641
  0.16344111 0.25876184 0.66385706 0.55482789]
 [0.56387213 0.84726814 0.27017851 0.32375281 0.         0.85815763
  0.26158106 0.23626934 0.84208647 0.55558831]
 [0.66546838 0.22418954 0.60711009 0.63851641 0.85815763 0.
  0.80166949 0.89388889 0.12095837 0.50641655]
 [0.72954411 0.85981685 0.22803883 0.16344111 0.26158106 0.80166949
  0.         0.09874537 0.82326113 0.66529097]
 [0.76359346 0.94040637 0.30209362 0.25876184 0.23626934 0.89388889
  0.09874537 0.         0.90966456 0.71811334]
 [0.57393374 0.10330456 0.6112835  0.66385706 0.84208647 0.12095837
  0.82326113 0.90966

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [51]:
x = np.arange(10, dtype = np.float32)
print(x)
print(type(x))

x = x.astype(np.int32, copy = False)
print(type(x))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [52]:
from io import StringIO
 
f = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

s = np.genfromtxt(f, delimiter=",", dtype=np.int)
print(s)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-52-c2c0231008dc>:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  s = np.genfromtxt(f, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [53]:
arr = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(arr):
    print(index, value)
    
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [54]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

D = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
G2 = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G2)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [55]:
n = 10
p = 3
arr = np.random.random((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace = False),1)
print(arr)

[[0.42170697 0.22627831 0.60247316 0.47414595 0.20907123 0.19762881
  0.13430476 0.04716253 0.1059254  0.98986169]
 [0.62103295 0.63094855 0.62572419 0.72340094 0.8635113  0.74105154
  0.23760597 0.20070308 0.22478331 0.91798068]
 [0.66499982 0.83557714 0.33867999 0.6405107  0.34041401 0.5154018
  0.40158614 0.43206951 0.61698619 0.89188581]
 [0.17226644 0.0763782  0.85106134 0.12107759 0.03726786 0.19041783
  0.04473566 0.07266532 0.62915076 0.28770711]
 [1.         0.77660269 0.94997263 0.18183391 0.99431712 0.85015717
  0.41902321 0.45514496 0.70582401 0.09257024]
 [0.57867789 0.64999202 0.39283803 0.00442344 0.62094392 0.25376231
  0.19894277 0.39514942 0.24345768 0.00606774]
 [0.00604299 0.19776434 0.67182414 0.35456183 0.93521264 1.
  0.79184518 0.45424736 0.40377088 0.99256071]
 [0.21549885 0.65795179 0.13030122 0.19442019 0.28978324 0.79493829
  0.20931016 0.92264462 0.40331243 0.0506226 ]
 [1.         0.7932306  0.05195646 0.54462458 0.78553158 0.99839959
  0.63301772 0.946738

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [56]:
mat = np.random.rand(5, 10)

# substracting each element from mean
m = mat - mat.mean(axis=1, keepdims=True)
print(Y)

[[0.14390329 0.65360607 0.29124576 0.34124577 0.02430394 0.78930495
  0.21906725 0.12782776 0.71383472 0.29241419]]


#### 59. How to sort an array by the nth column? (★★☆)

In [57]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[2 5 0]
 [3 0 5]
 [4 8 6]]
[[3 0 5]
 [2 5 0]
 [4 8 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [58]:
Z = np.random.randint(0,3,(3,10))

#checking for null values
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [59]:
arr = np.random.uniform(0,1,10)
ele = 0.5
v = arr.flat[np.abs(arr - ele).argmin()]
print(v)

0.5079011800089596


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [60]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])

for i,j,k in it: k[...] = i + j
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [61]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [62]:
vec = np.ones(10)
y = np.random.randint(0,len(Z),20)

np.add.at(vec, y, 1)
print(vec)

[4. 3. 3. 3. 3. 2. 2. 4. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [63]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [64]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

#computing 256*256 first to avoid overflow
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [65]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis = (-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis = -1)
print(sum)

[[45 48 37 55]
 [63 61 55 48]
 [47 56 32 72]]
[[45 48 37 55]
 [63 61 55 48]
 [47 56 32 72]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [66]:
import pandas as pd

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

print(pd.Series(D).groupby(S).mean())

[0.43428765 0.46495504 0.424845   0.5395913  0.55235843 0.44975618
 0.42431103 0.43986032 0.48999623 0.41228432]
0    0.434288
1    0.464955
2    0.424845
3    0.539591
4    0.552358
5    0.449756
6    0.424311
7    0.439860
8    0.489996
9    0.412284
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [67]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.sum(A * B.T, axis=1)

array([0.19763797, 0.94654828, 2.12894955, 1.32741944, 1.20743758])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [68]:
x = np.array([1,2,3,4,5])
d = 3
y = np.zeros(len(x) + (len(x)-1)*(d))
y[::d+1] = x
print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [69]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [70]:
A = np.arange(25).reshape(5,5)
print("Before Swaping :",A)

A[[0,1]] = A[[1,0]]
print("After Swaping :",A)

Before Swaping : [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After Swaping : [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [71]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 30) ( 0, 59) ( 8, 25) ( 8, 63) ( 9, 17) ( 9, 42) (17, 42) (24, 29)
 (24, 77) (25, 63) (29, 77) (30, 59) (31, 69) (31, 70) (33, 56) (33, 97)
 (41, 63) (41, 81) (44, 91) (44, 92) (46, 65) (46, 74) (47, 66) (47, 76)
 (56, 97) (63, 81) (65, 74) (66, 76) (69, 70) (91, 92)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [72]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [73]:
def moving_avg(a, n=3) :
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_avg(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [74]:
from numpy.lib import stride_tricks

def roll(a, w):
    shape = (a.size - w + 1, w)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape = shape, strides = strides)
Z = roll(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [75]:
b = np.random.randint(0,2,100)
np.logical_not(b, out = b)

b = np.random.uniform(-1.0,1.0,100)
np.negative(b, out = b)

array([-0.31477781,  0.95680807,  0.43194859,  0.59627289,  0.4330125 ,
        0.86412441,  0.44621939,  0.71548214, -0.67142466,  0.26396115,
        0.99300712, -0.77396086,  0.8284544 ,  0.45854428, -0.23662813,
        0.39058552,  0.5724425 ,  0.44130836, -0.88940772, -0.21277756,
        0.73469727, -0.75332167, -0.23501676,  0.22177384, -0.64836111,
        0.77629351, -0.95378282, -0.1254846 ,  0.25670171, -0.2078044 ,
       -0.28518898,  0.58094622,  0.06545037, -0.68550827,  0.25943172,
       -0.01640412,  0.75810532, -0.49543585,  0.85784949, -0.50360336,
       -0.60779331, -0.3575702 , -0.31795412, -0.02192848,  0.14298287,
        0.32835292,  0.25226126, -0.37232424, -0.9878983 ,  0.47670367,
        0.96057418,  0.95656226, -0.76232151, -0.28643913,  0.44808865,
        0.21235553,  0.34134179, -0.22591351, -0.036517  , -0.83450444,
       -0.34554714, -0.83804666,  0.75899405, -0.38128917,  0.86881512,
       -0.75466185, -0.77501975, -0.61692909, -0.83559622,  0.43

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [76]:
def dist(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(dist(P0, P1, p))

[ 6.01989888  6.12607526  5.21470927 14.33298284  0.0375335   7.29425291
  0.08419163  7.40822737  4.87785157  3.36280387]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [77]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))

print(np.array([dist(P0,P1,i) for i in p]))

[[ 5.72653088 11.66568825 15.47362117  6.71756892  6.86408383 10.9497463
   6.5362922   2.37376353  2.60487673 14.05594036]
 [ 0.50959079  5.75462954  8.66455678  4.96538196  0.28606501  4.30670253
   0.6129297   3.4943614   1.12874534  7.24645587]
 [10.95285241  0.07440095  1.21266438  8.02066856  7.91275418  4.21282346
  11.02204942 10.91042442  6.75333495  2.98246337]
 [ 0.56277826  3.35005997  6.98365668  2.60565741  1.80030917  2.28222449
   0.19829665  1.77718599  2.74103351  5.68633982]
 [ 1.11928006 14.75432226 14.2400001  14.87970773  7.70737154 11.43828
   0.85359746 11.34955841  6.36000557 12.29033613]
 [ 5.24303581  7.76795944  7.21457623 11.26264957  0.48613898  4.22313267
   4.27449524 10.63401504  6.0273643   5.37796588]
 [ 0.62473501  4.24468117  1.62151891  4.76716633  8.41877639  4.14505244
   1.20854411  3.54052862  7.72552875  0.69979825]
 [ 5.96375671  2.0504245   0.11840423  2.33744117  8.28714374  4.33550471
   6.82762916  4.55928712  0.39804771  1.5139752 ]
 [ 1

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [78]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 3 5 3 7 3 8 9 8 2]
 [9 7 5 7 6 2 1 5 7 4]
 [3 3 7 1 4 8 7 1 0 6]
 [1 3 4 0 0 2 1 1 2 8]
 [8 2 1 1 7 4 6 7 7 0]
 [7 4 3 3 5 7 1 6 1 0]
 [2 3 1 9 0 9 6 9 3 2]
 [6 7 7 2 7 6 8 3 2 0]
 [6 6 2 3 5 1 8 4 8 1]
 [8 1 7 3 2 5 4 9 8 7]]
[[0 0 0 0 0]
 [0 8 3 5 3]
 [0 9 7 5 7]
 [0 3 3 7 1]
 [0 1 3 4 0]]


<ipython-input-78-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [79]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [80]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [81]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [82]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape = (i, j, n, n), strides = Z.strides + Z.strides)

print(C)

[[[[2 0 3]
   [1 1 1]
   [4 3 2]]

  [[0 3 2]
   [1 1 0]
   [3 2 4]]

  [[3 2 1]
   [1 0 3]
   [2 4 3]]

  [[2 1 1]
   [0 3 0]
   [4 3 2]]

  [[1 1 4]
   [3 0 3]
   [3 2 2]]

  [[1 4 3]
   [0 3 3]
   [2 2 1]]

  [[4 3 4]
   [3 3 1]
   [2 1 3]]

  [[3 4 0]
   [3 1 0]
   [1 3 3]]]


 [[[1 1 1]
   [4 3 2]
   [1 4 3]]

  [[1 1 0]
   [3 2 4]
   [4 3 1]]

  [[1 0 3]
   [2 4 3]
   [3 1 4]]

  [[0 3 0]
   [4 3 2]
   [1 4 2]]

  [[3 0 3]
   [3 2 2]
   [4 2 1]]

  [[0 3 3]
   [2 2 1]
   [2 1 1]]

  [[3 3 1]
   [2 1 3]
   [1 1 0]]

  [[3 1 0]
   [1 3 3]
   [1 0 1]]]


 [[[4 3 2]
   [1 4 3]
   [0 0 3]]

  [[3 2 4]
   [4 3 1]
   [0 3 1]]

  [[2 4 3]
   [3 1 4]
   [3 1 1]]

  [[4 3 2]
   [1 4 2]
   [1 1 0]]

  [[3 2 2]
   [4 2 1]
   [1 0 4]]

  [[2 2 1]
   [2 1 1]
   [0 4 1]]

  [[2 1 3]
   [1 1 0]
   [4 1 3]]

  [[1 3 3]
   [1 0 1]
   [1 3 4]]]


 [[[1 4 3]
   [0 0 3]
   [0 4 3]]

  [[4 3 1]
   [0 3 1]
   [4 3 0]]

  [[3 1 4]
   [3 1 1]
   [3 0 2]]

  [[1 4 2]
   [1 1 0]
   [0 2 3]]

  [[4 2 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [83]:
class Darray(np.ndarray):
    def item(self, index, value):
        i,j = index
        super(Darray, self).item((i,j), value)
        super(Darray, self).item((j,i), value)

def D(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Darray)

S = D(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 14 12 10 11]
 [14  3  0 12 11]
 [12  0  7 42  9]
 [10 12  8  7  7]
 [11 11  9  7  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [84]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [85]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [86]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [87]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9997 9998 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [88]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [89]:
arr = np.array([("Python", 2.5, 3),
              ("Program", 3.6, 2)])
record = np.core.records.fromarrays(arr.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(record)

[(b'Python', 2.5, 3) (b'Program', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [90]:
x = np.random.rand(10000)

%timeit np.power(x,3)                   #Method 1
%timeit x*x*x                           #Method 2
%timeit np.einsum('i,i,i->i',x,x,x)     #Method 3

770 µs ± 47.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
22.2 µs ± 584 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
32.8 µs ± 2.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [91]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [92]:
mat = np.random.randint(0,5,(10,3))
print(mat)

E = np.all(mat[:,1:] == mat[:,:-1], axis=1)
U = mat[~E]
print(U)

[[4 1 2]
 [2 4 2]
 [4 2 3]
 [0 1 2]
 [0 2 0]
 [3 0 3]
 [2 0 1]
 [3 0 4]
 [1 4 1]
 [1 4 2]]
[[4 1 2]
 [2 4 2]
 [4 2 3]
 [0 1 2]
 [0 2 0]
 [3 0 3]
 [2 0 1]
 [3 0 4]
 [1 4 1]
 [1 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [93]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype = np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis = 1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [94]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)

print(uZ)

[[0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [95]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)         # np.sum(A)
np.einsum('i,i->i', A, B)   # A * B
np.einsum('i,i', A, B)      # np.inner(A, B)
np.einsum('i,j->ij', A, B)  # np.outer(A, B)

array([[0.1679486 , 0.0795528 , 0.31918752, 0.52764941, 0.36478259,
        0.1567109 , 0.10484657, 0.12893525, 0.28887597, 0.20757644],
       [0.00745868, 0.00353298, 0.01417527, 0.02343316, 0.01620017,
        0.00695961, 0.00465629, 0.00572608, 0.01282912, 0.00921857],
       [0.25952817, 0.12293162, 0.49323515, 0.81536783, 0.56369245,
        0.24216273, 0.16201765, 0.19924149, 0.44639523, 0.32076442],
       [0.26164836, 0.1239359 , 0.49726459, 0.82202891, 0.56829749,
        0.24414106, 0.16334124, 0.20086918, 0.45004201, 0.32338487],
       [0.25622576, 0.12136735, 0.48695889, 0.80499254, 0.55651964,
        0.23908129, 0.15995603, 0.19670621, 0.44071499, 0.31668279],
       [0.1189433 , 0.05634029, 0.22605259, 0.37368791, 0.25834359,
        0.11098461, 0.07425365, 0.09131355, 0.20458557, 0.14700823],
       [0.03976147, 0.01883395, 0.07556696, 0.12491986, 0.08636149,
        0.03710097, 0.0248222 , 0.03052514, 0.06839077, 0.04914328],
       [0.08165563, 0.03867811, 0.1551871

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [96]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5   #segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                   #integrate path
r_int = np.linspace(0, r.max(), 200)    #regular spaced path
x_int = np.interp(r_int, r, x)          #integrate path
y_int = np.interp(r_int, r, y)

print(r_int,x_int,y_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [97]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis = -1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [98]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.22594859  0.14730825]
